[package]
name = "nextbike"
version = "0.1.0"
edition = "2021"
default-run = "nextbike"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.150"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.6", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["blocking" ] }
regex = "1.12.3"
env_logger = "0.9.3"
log = "0.4.30"
lazy_static = "1.5.0"
chrono = "0.4.44"
byteorder = "1.5.0"
actix-web = "4"
actix-files = "0.6.10"
memmap = "0.7.0"
