name: build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    tags: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_nextbike_server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - run: sudo apt-get install -y gcc-aarch64-linux-gnu
    - run: rustup target add aarch64-unknown-linux-gnu
    - run: cargo build --release --target aarch64-unknown-linux-gnu --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: nextbike_server
        path: target/aarch64-unknown-linux-gnu/release/nextbike
    
  build_viewer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: viewer
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: viewer
        path: viewer/dist/
        
  deploy:
    runs-on: ubuntu-latest
    needs:
     - build_nextbike_server
     - build_viewer
    steps:
      - uses: actions/download-artifact@v3
      - run: find
      - run: 'tar -cfJ viewer.tar.xz viewer'
      - run: 'curl --fail -s -H"Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" -F nextbike_server=@nextbike_server/nextbike -F viewer.tar.xz=@viewer.tar.xz https://trnila.eu/hooks/nextbike'
