name: parser

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - run: rustup target add aarch64-unknown-linux-gnu
    - run: cargo build --release --target aarch64-unknown-linux-gnu --verbose
    
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          target/aarch64-unknown-linux-gnu/release/nextbike
